### PR TITLE
Added capacitor and iOS documentation

### PR DESCRIPTION
**Pull request by jabelone**
Added documentation to cover the following things:
* How to install as a Capacitor plugin
* How to import and use as a Capacitor plugin
* How to configure the iOS `Info.plist` file to avoid unhelpful `null` errors

### CODE REVIEW

**Review by emcniece — APPROVED** [review]
Fantastic! Thank you for the help :)

**Comment by jabelone** [comment]
Firstly, thanks for this great plugin! I wasted a few hours of trying to work out why I kept getting this very unhelpful `null` error printed in the console when trying to watch or publish a service. It turns out that you now (not sure since when) need to configure the Info.plist file correctly. Hopefully this stops someone else from the frustration :)

**Comment by emcniece** [comment]
That `plist` change is new to me as well, nice sleuthing.

**Comment by jabelone** [comment]
> Fantastic! Thank you for the help :)

No problem! Thanks for the plugin, it made it super easy to implement auto discovery for my battery charger app once I got it working. 😄

**Pull request merged**
